"""init_vault_schema"""

from __future__ import annotations

from typing import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str | None = '362353113c61'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pii_tokens',
    sa.Column('token', sa.String(length=20), nullable=False),
    sa.Column('prefix', sa.String(length=3), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('normalized_value', sa.Text(), nullable=False),
    sa.Column('canonical_value', sa.Text(), nullable=True),
    sa.Column('encrypted_value', sa.LargeBinary(), nullable=True),
    sa.Column('pepper_version', sa.String(length=10), nullable=False),
    sa.Column('detector', sa.String(length=50), nullable=True),
    sa.Column('case_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index('idx_pii_tokens_digest', 'pii_tokens', ['digest'], unique=False)
    op.create_index('idx_pii_tokens_prefix', 'pii_tokens', ['prefix'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_pii_tokens_prefix', table_name='pii_tokens')
    op.drop_index('idx_pii_tokens_digest', table_name='pii_tokens')
    op.drop_table('pii_tokens')
    # ### end Alembic commands ###
